import type { Metadata } from "next";
import "./globals.css";
import StatusBar from "./components/status-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <div>
          <StatusBar />
          {children}
        </div>
      </body>
    </html>
  );
}
